---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pinpt.full_name" . }}-oklog
  labels:
    app: {{ template "pinpt.full_name" . }}-oklog
    component: oklog
    {{- include "pinpt.release_labels" . | indent 4 }}
{{- $nodeCount := .Values.oklog.replicas | int }}
data:
  start.sh: |
     #!/bin/sh
     /oklog ingeststore \
      -api tcp://${POD_IP}:7650 \
      -ingest.fast tcp://${POD_IP}:7651 \
      -ingest.durable tcp://${POD_IP}:7652 \
      -ingest.bulk tcp://${POD_IP}:7653 \
      -debug \
      -cluster tcp://${POD_IP}:7659 \
      -store.segment-target-size {{ .Values.oklog.config.targetSize }} \
      -store.segment-replication-factor {{ .Values.oklog.config.replicationFactor }} \
      -store.segment-retain {{ .Values.oklog.config.retention }} \
      -store.segment-purge {{ .Values.oklog.config.purge }} \
      -ingest.path               /data/ingest \
      -store.path                /data/store \
     {{- range $i := until $nodeCount }}
      -peer {{ template "pinpt.full_name" $ }}-oklog-{{$i}}.{{ template "pinpt.full_name" $ }}-oklog.{{ $.Release.Namespace }}.svc.cluster.local:7659 \
     {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "pinpt.full_name" . }}-oklog
  labels:
    app: {{ template "pinpt.full_name" . }}-oklog
    component: oklog
    {{- include "pinpt.release_labels" . | indent 4 }}
spec:
  clusterIP: None
  ports:
    - name: api
      port: 7650
      targetPort: 7650
      protocol: TCP
    - name: ingest-fast
      port: 7651
      targetPort: 7651
      protocol: TCP
    - name: ingest-durable
      port: 7652
      targetPort: 7652
      protocol: TCP
    - name: ingest-bulk
      port: 7653
      targetPort: 7653
      protocol: TCP
    - name: ingest-cluster
      port: 7659
      targetPort: 7659
      protocol: TCP
    - name: ingest-cluster-udp
      port: 7659
      targetPort: 7659
      protocol: UDP
  selector:
    app: {{ template "pinpt.full_name" . }}-oklog

{{- if .Values.loadBalancerService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "pinpt.full_name" . }}-oklog-lb
  labels:
    app: {{ template "pinpt.full_name" . }}-oklog-lb
    component: oklog
    {{- include "pinpt.release_labels" . | indent 4 }}
{{- if .Values.loadBalancerService.annotations }}
  annotations:
{{ toYaml .Values.loadBalancerService.annotations | indent 4 }}
{{- end}}
spec:
  ports:
    - name: api
      port: 7650
      targetPort: 7650
      protocol: TCP
    - name: ingest-fast
      port: 7651
      targetPort: 7651
      protocol: TCP
  type: LoadBalancer
  selector:
    app: {{ template "pinpt.full_name" . }}-oklog
{{- end }}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "pinpt.full_name" . }}-oklog
  labels:
    app: {{ template "pinpt.full_name" . }}-oklog
    component: oklog
    {{- include "pinpt.release_labels" . | indent 4 }}
spec:
  serviceName: {{ template "pinpt.full_name" . }}-oklog
  replicas: {{ .Values.oklog.replicas }}
  selector:
    matchLabels:
      app: {{ template "pinpt.full_name" . }}-oklog
  template:
    metadata:
      name: {{ template "pinpt.full_name" . }}-oklog
      labels:
        app: {{ template "pinpt.full_name" . }}-oklog
        component: oklog
        {{- include "pinpt.release_labels" . | indent 8 }}
    spec:
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      volumes:
        - name: oklog-configmap
          configMap:
            name: {{ template "pinpt.full_name" . }}-oklog
      containers:
        - name: oklog
          image: {{ .Values.oklog.image.repository }}:{{ .Values.oklog.image.tag }}
          imagePullPolicy: {{ .Values.oklog.image.pullPolicy }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command:
            - /bin/sh
            - /go/bin/start.sh
          volumeMounts:
{{- if .Values.persistence.enabled }}
            - name: export
              mountPath: {{ .Values.persistence.mountPath }}
{{- end }}
            - name: oklog-configmap
              mountPath: /go/bin/start.sh
              subPath: start.sh
          ports:
            - name: api
              containerPort: 7650
            - name: ingest-fast
              containerPort: 7651
            - name: ingest-durable
              containerPort: 7652
            - name: ingest-bulk
              containerPort: 7653
            - name: cluster
              containerPort: 7659
          resources:
{{ toYaml .Values.oklog.resources | indent 12}}
{{- if  .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: export
    spec:
      accessModes:
        - {{ .Values.persistence.accessMode | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
{{- if .Values.persistence.storageClass}}
{{- if (eq "-" .Values.persistence.storageClass) }}
      storageClassName: ""
{{- else }}
      storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end -}}
{{- end -}}
{{- end -}}
